* I/O AND BUGFIX PATCH FOR NAKAMOZU TINY BASIC V6.0
* NTB BY HARUO YAMASHITA, OCT, 1978
* PATCH FOR MIKBUG/SWTBUG BY DAVE HASSLER, 2025

INEEE	EQU	$E1AC	SWTBUG
OUTEEE	EQU	$E1D1	   "
CONTRL	EQU	$E0E3	   "
ACIACS	EQU	$8018	WHERE MY ODD 6850 IS...
ACIADA 	EQU	$8019
IN_3	EQU	$0161	CHECK FOR CTRL-C IN "IN" LABEL

	ORG	$013D
	CMPA	#$08	RUBOUT IS NOW BACKSPACE

	ORG	$0149
	FCB	$20,$23	'BRA CR1' (FIXES CRLF)

	ORG	$015E
	JSR	INEEE	FOR SWTBUG TTY INPUT

	ORG	$0185
	JSR	NEWBRK	OLD BRK WAS PIA-BASED
	JSR	IN_3	IS #03? (DURING DIRECT INPUT)
	NOP

	ORG	$01B2
	NOP		KILL CUSTOM ROM CALL (INIT)
	NOP
	NOP

	ORG	$046A
	JMP	OUTEEE	FOR SWTBUG TTY OUTPUT

	ORG	$098C
NEWBRK	LDAA	ACIACS	LOC. WAS 'COPY' STMT, USED TO
	ASRA		   COPY SCREEN DISPLAY TO PRINTER
	BCC	NO_BRK
	LDAA	ACIADA
NO_BRK	RTS

	ORG	$0B61
	FDB	$E0E3	SWTBUG 'CONTRL' FOR EXIT STMT.
