
* New KEY routine for Nakamozu Tiny BASIC.
* Works sort of like GET$ in Commodore BASIC v2.
* Polls ACIA, returns a character; otherwise, returns a 0.
* 1/20 second delay seems OK, but feel free to tweak it.
* Patch by Dave Hassler, 2025

ACIACS	EQU	$8018	WHERE MY FUNKY 6850 LIVES...
ACIADA 	EQU	$8019
CPS2	EQU	$05E4	STORE CHAR IN A VARIB ROUTINE
WKC	EQU	$54	NTB'S THIRD WORK VARIB (2 BYTES)
*
	ORG	$0AEF	START ORIGINAL 'KEY' FUNC.
	BSR	DELAY	WAIT A BIT, THEN...
	LDAA	ACIACS	CHECK FOR A CHAR RECEIVED BY
	ASRA		  SLIDING BYTE RIGHT INTO CARRY
	BCC	NO_CHAR	NOTHING THERE, SET ACCA 0
	LDAA	ACIADA	SOMETHING THERE, GET THE CHAR
	BRA	SETUP	  AND GO AROUND
NO_CHAR	LDAA	#0	0=NOTHING THERE
SETUP	CLRB		CLEAR MSB TO ENSURE RESULT <256
	JMP	CPS2	GO STORE IT IN USER'S VARIABLE
*
DELAY	STX	WKC
	LDX	#$28F5	1/20 SEC. $51EB=1/10 $8888=1/6
LOOP	DEX
	BNE	LOOP
	LDX	WKC
	RTS
